name: Audit Logging Build and Test

on:
  push:
    branches:
      - master
      - v*.*
  pull_request:
    branches:
      - master
      - v*.*

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: ["8.0", "8.1"]
        laravel: ["^6.0", "^7.0", "^8.0", "^9.0", "^10.0"]
        testbench: ["^4.0", "^5.0", "^6.0", "^7.0", "^8.0"]
        include:
          - php: "8.0"
            laravel: "^8.0"
            testbench: "^6.0"
          - php: "8.1"
            laravel: "^9.0"
            testbench: "^7.0"
          - php: "8.1"
            laravel: "^10.0"
            testbench: "^8.0"
        exclude:
          # Laravel 6 & 7 only support up to PHP 7.4, so always exclude
          - php: "8.0"
            laravel: "^6.0"
          - php: "8.1"
            laravel: "^6.0"
          - php: "8.0"
            laravel: "^7.0"
          - php: "8.1"
            laravel: "^7.0"
          # Laravel 10: needs PHP 8.1+
          - php: "8.0"
            laravel: "^10.0"

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install required package
        run: "composer require --no-interaction --no-update orchestra/testbench:${{ matrix.testbench }}"

      - name: Install dependencies
        run: "composer update --with='illuminate/contracts:${{ matrix.laravel }}' --prefer-dist --no-interaction --no-progress --no-dev"

      - name: Execute tests via PHPUnit
        run: vendor/bin/phpunit