name: Audit Logging Build and Test

on:
  push:
    branches:
      - master
      - v*.*
  pull_request:
    branches:
      - master
      - v*.*

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: ["8.1", "8.2"]
        laravel_version: ["^10.0","^11.0"]
        testbench_version: ["^8.0","^9.0"]
        
        include:
          # PHP 8.1 with Laravel 10.x requires Testbench ^6.0
          - php: "8.1"
            laravel_version: "10.x"
            testbench_version: "^8.0" 
          
          # PHP 8.2 with Laravel 11.x requires Testbench ^7.0
          - php: "8.2"
            laravel_version: "10.x"
            testbench_version: "^8.0"            

          - php: "8.2"
            laravel_version: "11.x"
            testbench_version: "^9.0" 

        exclude:
          # Laravel 11.x and 12.x require PHP 8.2 or newer, so exclude them from PHP 8.1 builds
          - php: "8.1"
            laravel_version: "11.x"

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: "composer require --dev \"laravel/framework:${{ matrix.laravel_version }}\" --no-update --no-interaction --prefer-dist && composer require --dev \"orchestra/testbench:${{ matrix.testbench_version }}\" --no-update --no-interaction --prefer-dist && composer update --prefer-dist --no-interaction --no-progress"

      - name: Execute tests via PHPUnit
        run: vendor/bin/phpunit